//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.GameCore.PlayerCard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlayerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.GameCore.PlayerCard.PlayerResources", typeof(PlayerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Stat.
        /// </summary>
        internal static string ActiveStat {
            get {
                return ResourceManager.GetString("ActiveStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} burned their momentum ({1}).
        /// </summary>
        internal static string BurnMomentumMessage {
            get {
                return ResourceManager.GetString("BurnMomentumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debilities.
        /// </summary>
        internal static string Debilities {
            get {
                return ResourceManager.GetString("Debilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reply to a player card to set the debilities for that card..
        /// </summary>
        internal static string DebilityMissingPlayerCard {
            get {
                return ResourceManager.GetString("DebilityMissingPlayerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge.
        /// </summary>
        internal static string Edge {
            get {
                return ResourceManager.GetString("Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart.
        /// </summary>
        internal static string Heart {
            get {
                return ResourceManager.GetString("Heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Card Helper.
        /// </summary>
        internal static string HelperTitle {
            get {
                return ResourceManager.GetString("HelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        internal static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentum.
        /// </summary>
        internal static string Momentum {
            get {
                return ResourceManager.GetString("Momentum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Card.
        /// </summary>
        internal static string PlayerCardTitle {
            get {
                return ResourceManager.GetString("PlayerCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        internal static string Shadow {
            get {
                return ResourceManager.GetString("Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit.
        /// </summary>
        internal static string Spirit {
            get {
                return ResourceManager.GetString("Spirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impacts.
        /// </summary>
        internal static string StarforgedDebilities {
            get {
                return ResourceManager.GetString("StarforgedDebilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}, {2}: {3}, {4}: {5}, {6}: {7}, {8}: {9}.
        /// </summary>
        internal static string StatsFormat {
            get {
                return ResourceManager.GetString("StatsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply.
        /// </summary>
        internal static string Supply {
            get {
                return ResourceManager.GetString("Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many stats are active, please disable all but one..
        /// </summary>
        internal static string TooManyStatsActive {
            get {
                return ResourceManager.GetString("TooManyStatsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wits.
        /// </summary>
        internal static string Wits {
            get {
                return ResourceManager.GetString("Wits", resourceCulture);
            }
        }
    }
}
