//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.StarForged.Creatures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreatureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.StarForged.Creatures.CreatureResources", typeof(CreatureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicForm.
        /// </summary>
        internal static string BasicForm {
            get {
                return ResourceManager.GetString("BasicForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature Helper.
        /// </summary>
        internal static string CreatureHelper {
            get {
                return ResourceManager.GetString("CreatureHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Starforged Creature__.
        /// </summary>
        internal static string CreatureTitle {
            get {
                return ResourceManager.GetString("CreatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered Behavior.
        /// </summary>
        internal static string EncounteredBehavior {
            get {
                return ResourceManager.GetString("EncounteredBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Look.
        /// </summary>
        internal static string FirstLook {
            get {
                return ResourceManager.GetString("FirstLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick the creature&apos;s environment:
        ///1️⃣ - Void
        ///2️⃣ - Interior
        ///3️⃣ - Land
        ///4️⃣ - Liquid
        ///5️⃣ - Air
        ///🎲 - Random.
        /// </summary>
        internal static string PickCreatureEnvironmentMessage {
            get {
                return ResourceManager.GetString("PickCreatureEnvironmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revealed Aspect.
        /// </summary>
        internal static string RevealedAspect {
            get {
                return ResourceManager.GetString("RevealedAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed: {0}.
        /// </summary>
        internal static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
    }
}
