// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TheOracle.Migrations
{
    [DbContext(typeof(DiscordChannelContext))]
    [Migration("20201027171014_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("TheOracle.BotCore.ChannelSettings", b =>
                {
                    b.Property<ulong>("ChannelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultGame")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RerollDuplicates")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelID");

                    b.ToTable("ChannelSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
