//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.StarForged.PlayerShips {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlayerShipResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerShipResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.StarForged.PlayerShips.PlayerShipResources", typeof(PlayerShipResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reply in this channel with the requested information.
        /// </summary>
        public static string HelperFooter {
            get {
                return ResourceManager.GetString("HelperFooter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to use your starship to keep track of you/your crew&apos;s supply? Reply with `Yes` to enable, or `No` to disable..
        /// </summary>
        public static string HelperIncludeSupply {
            get {
                return ResourceManager.GetString("HelperIncludeSupply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Give your starship some history. Type something about how you got the ship, or its history. To use the Ship history oracle table reply with `random`. To leave this blank reply with `skip`..
        /// </summary>
        public static string HelperSetHistory {
            get {
                return ResourceManager.GetString("HelperSetHistory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Describe what your starship looks like. Type something about how your starship looks, or what gives it character. To use the Envision Your Starship oracle table reply with `random`. To leave this blank reply with `skip`..
        /// </summary>
        public static string HelperSetLooks {
            get {
                return ResourceManager.GetString("HelperSetLooks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the name of your ship?.
        /// </summary>
        public static string HelperSetShipName {
            get {
                return ResourceManager.GetString("HelperSetShipName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command Ship Helper.
        /// </summary>
        public static string HelperTitle {
            get {
                return ResourceManager.GetString("HelperTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Impacts.
        /// </summary>
        public static string Impacts {
            get {
                return ResourceManager.GetString("Impacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integrity.
        /// </summary>
        public static string Integrity {
            get {
                return ResourceManager.GetString("Integrity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integrity Meter.
        /// </summary>
        public static string IntegrityMeter {
            get {
                return ResourceManager.GetString("IntegrityMeter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Random, Rand.
        /// </summary>
        public static string RandomWords {
            get {
                return ResourceManager.GetString("RandomWords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ship So Far.
        /// </summary>
        public static string SelectedItems {
            get {
                return ResourceManager.GetString("SelectedItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command Starship.
        /// </summary>
        public static string ShipCardTitle {
            get {
                return ResourceManager.GetString("ShipCardTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to History: {0}.
        /// </summary>
        public static string ShipHistory {
            get {
                return ResourceManager.GetString("ShipHistory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description: {0}.
        /// </summary>
        public static string ShipLooks {
            get {
                return ResourceManager.GetString("ShipLooks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipWords {
            get {
                return ResourceManager.GetString("SkipWords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supply.
        /// </summary>
        public static string Supply {
            get {
                return ResourceManager.GetString("Supply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supply Meter.
        /// </summary>
        public static string SupplyMeter {
            get {
                return ResourceManager.GetString("SupplyMeter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes, True.
        /// </summary>
        public static string YesWords {
            get {
                return ResourceManager.GetString("YesWords", resourceCulture);
            }
        }
    }
}
