//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.StarForged.Planets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlanetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanetResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.StarForged.Planets.PlanetResources", typeof(PlanetResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere.
        /// </summary>
        internal static string Atmosphere {
            get {
                return ResourceManager.GetString("Atmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biome.
        /// </summary>
        internal static string Biome {
            get {
                return ResourceManager.GetString("Biome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closer Look.
        /// </summary>
        internal static string CloserLook {
            get {
                return ResourceManager.GetString("CloserLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string HelperOptions {
            get {
                return ResourceManager.GetString("HelperOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a space region:
        ///1️⃣ - Termnius
        ///2️⃣ - Outlands
        ///3️⃣ - Expanse.
        /// </summary>
        internal static string HelperText {
            get {
                return ResourceManager.GetString("HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life.
        /// </summary>
        internal static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Planet Helper__.
        /// </summary>
        internal static string PlanetHelperTitle {
            get {
                return ResourceManager.GetString("PlanetHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Planet.
        /// </summary>
        internal static string PlanetPostDescription {
            get {
                return ResourceManager.GetString("PlanetPostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlements.
        /// </summary>
        internal static string Settlements {
            get {
                return ResourceManager.GetString("Settlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Observation {0}.
        /// </summary>
        internal static string SpaceObservation {
            get {
                return ResourceManager.GetString("SpaceObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
