//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.GameCore.ProgressTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgressResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgressResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.GameCore.ProgressTracker.ProgressResources", typeof(ProgressResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an objective tracking post for things like Iron Vows.
        /// </summary>
        internal static string CommandDesc {
            get {
                return ResourceManager.GetString("CommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous.
        /// </summary>
        internal static string Dangerous {
            get {
                return ResourceManager.GetString("Dangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic.
        /// </summary>
        internal static string Epic {
            get {
                return ResourceManager.GetString("Epic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        internal static string Extreme {
            get {
                return ResourceManager.GetString("Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formidable.
        /// </summary>
        internal static string Formidable {
            get {
                return ResourceManager.GetString("Formidable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Amount.
        /// </summary>
        internal static string Progress_Amount {
            get {
                return ResourceManager.GetString("Progress Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Bar.
        /// </summary>
        internal static string Progress_Bar {
            get {
                return ResourceManager.GetString("Progress Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Tracker.
        /// </summary>
        internal static string Progress_Tracker {
            get {
                return ResourceManager.GetString("Progress Tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactions.
        /// </summary>
        internal static string Reactions {
            get {
                return ResourceManager.GetString("Reactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troublesome.
        /// </summary>
        internal static string Troublesome {
            get {
                return ResourceManager.GetString("Troublesome", resourceCulture);
            }
        }
    }
}
