//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.IronSworn.Delve {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DelveResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DelveResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.IronSworn.Delve.DelveResources", typeof(DelveResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 = Barrow
        ///2 = Cavern
        ///3 = Frozen Cavern
        ///4 = Icereach
        ///5 = Mine
        ///6 = Pass
        ///7 = Ruin
        ///8 = Sea Cave
        ///9 = Shadowfen
        ///10 = Stronghold
        ///11 = Tanglewood
        ///12 = Underkeep
        ///
        ///R = Random theme.
        /// </summary>
        internal static string DomainHelperText {
            get {
                return ResourceManager.GetString("DomainHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Domain.
        /// </summary>
        internal static string DomainHelperTitle {
            get {
                return ResourceManager.GetString("DomainHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to this message with the number of the action/theme you want. To add multiple themes/domains use a comma to seperate the entries like `1, R`.
        /// </summary>
        internal static string HelperFooter {
            get {
                return ResourceManager.GetString("HelperFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 = Ancient
        ///2 = Corrupted
        ///3 = Fortified
        ///4 = Hallowed
        ///5 = Haunted
        ///6 = Infested
        ///7 = Ravaged
        ///8 = Wild
        ///
        ///R = Random theme
        ///2R = Two random themes.
        /// </summary>
        internal static string ThemeHelperText {
            get {
                return ResourceManager.GetString("ThemeHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        internal static string ThemeHelperTitle {
            get {
                return ResourceManager.GetString("ThemeHelperTitle", resourceCulture);
            }
        }
    }
}
