//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.IronSworn.Delve {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DelveResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DelveResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.IronSworn.Delve.DelveResources", typeof(DelveResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **__{0}__**.
        /// </summary>
        internal static string CardSiteNameFormat {
            get {
                return ResourceManager.GetString("CardSiteNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delve Site - {0} : {1}.
        /// </summary>
        internal static string CardThemeDomainTitleFormat {
            get {
                return ResourceManager.GetString("CardThemeDomainTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Domain.
        /// </summary>
        internal static string DomainHelperTitle {
            get {
                return ResourceManager.GetString("DomainHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to this message with the number of the action/theme you want. To add multiple themes/domains use a comma to seperate the entries: 1, R.
        /// </summary>
        internal static string HelperFooterThemeDomain {
            get {
                return ResourceManager.GetString("HelperFooterThemeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the name of the site or use `Random` to generate the name from the site name oracle tables.
        /// </summary>
        internal static string HelperSiteNameText {
            get {
                return ResourceManager.GetString("HelperSiteNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Site Name.
        /// </summary>
        internal static string HelperSiteNameTitle {
            get {
                return ResourceManager.GetString("HelperSiteNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your objective for this delve site. The objective should be tied to your vow..
        /// </summary>
        internal static string HelperSiteObjectiveText {
            get {
                return ResourceManager.GetString("HelperSiteObjectiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Site Objective.
        /// </summary>
        internal static string HelperSiteObjectiveTitle {
            get {
                return ResourceManager.GetString("HelperSiteObjectiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either input the full name of the site rank or use the corresponding number:
        ///
        ///1 - Troublesome
        ///2 - Dangerous
        ///3 - Formidable
        ///4 - Extreme
        ///5 - Epic.
        /// </summary>
        internal static string HelperSiteRankText {
            get {
                return ResourceManager.GetString("HelperSiteRankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Site Rank.
        /// </summary>
        internal static string HelperSiteRankTitle {
            get {
                return ResourceManager.GetString("HelperSiteRankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string HelperTextFormat {
            get {
                return ResourceManager.GetString("HelperTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string ListSeperator {
            get {
                return ResourceManager.GetString("ListSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate your Objective roll for {0}.
        /// </summary>
        internal static string LocateObjectiveRoll {
            get {
                return ResourceManager.GetString("LocateObjectiveRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Amount.
        /// </summary>
        internal static string ProgressAmountField {
            get {
                return ResourceManager.GetString("ProgressAmountField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Track.
        /// </summary>
        internal static string ProgressTrackField {
            get {
                return ResourceManager.GetString("ProgressTrackField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R,Random,Rand,Roll.
        /// </summary>
        internal static string RandomAliases {
            get {
                return ResourceManager.GetString("RandomAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string RankField {
            get {
                return ResourceManager.GetString("RankField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal a Danger roll for {0}.
        /// </summary>
        internal static string RevealDangerRoll {
            get {
                return ResourceManager.GetString("RevealDangerRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal a Feature roll for {0}.
        /// </summary>
        internal static string RevealFeatureRoll {
            get {
                return ResourceManager.GetString("RevealFeatureRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Zone.
        /// </summary>
        internal static string RiskZoneField {
            get {
                return ResourceManager.GetString("RiskZoneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High (Formidable or Extreme).
        /// </summary>
        internal static string RiskZoneHigh {
            get {
                return ResourceManager.GetString("RiskZoneHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low (Troublesome or Dangerous).
        /// </summary>
        internal static string RiskZoneLow {
            get {
                return ResourceManager.GetString("RiskZoneLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (Dangerous or Formidable).
        /// </summary>
        internal static string RiskZoneMedium {
            get {
                return ResourceManager.GetString("RiskZoneMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        internal static string ThemeHelperTitle {
            get {
                return ResourceManager.GetString("ThemeHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain you tried to enter &apos;{0}&apos; doesn&apos;t have any matching items.
        /// </summary>
        internal static string UnknownDomainError {
            get {
                return ResourceManager.GetString("UnknownDomainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme you tried to enter &apos;{0}&apos; doesn&apos;t have any matching items.
        /// </summary>
        internal static string UnknownThemeError {
            get {
                return ResourceManager.GetString("UnknownThemeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not reply before the timeout, please start again..
        /// </summary>
        internal static string UserInputTimeoutError {
            get {
                return ResourceManager.GetString("UserInputTimeoutError", resourceCulture);
            }
        }
    }
}
