// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Dataforged
{
    /// <summary>
    /// Describes changes applied to an asset, usually by another asset.
    /// Unchanged properties are omitted.
    /// </summary>
    public class AssetExtensionForeign
    {
        /// <summary>
        /// The AssetId (wildcard?) that extends this
        /// </summary>
        [JsonPropertyName("extends")]
        public string Extends { get; set; }

        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("attachments")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AssetExtensionForeignAttachments Attachments { get; set; }

        [JsonPropertyName("condition_meter")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AssetExtensionForeignConditionMeter ConditionMeter { get; set; }

        [JsonPropertyName("count_as_impact")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? CountAsImpact { get; set; }
    }
}
