// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

namespace Dataforged
{
    public class OracleCollectionRoot
    {
        public Source Source { get; set; }
        public string Id { get; set; }
        public string Ruleset { get; set; }
        public Dictionary<string, OracleCollection> Oracles { get; set; }
    }
}
