//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.GameCore.SceneChallenge {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SceneChallengeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SceneChallengeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.GameCore.SceneChallenge.SceneChallengeResources", typeof(SceneChallengeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown Amount.
        /// </summary>
        internal static string CountdownAmount {
            get {
                return ResourceManager.GetString("CountdownAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown Track.
        /// </summary>
        internal static string CountdownTrack {
            get {
                return ResourceManager.GetString("CountdownTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A typical challenge is dangerous. Make it formidable if you are at a disadvantage, or troublesome if you have clear advantage..
        /// </summary>
        internal static string HelperAdditionalInfo {
            get {
                return ResourceManager.GetString("HelperAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve the scene roll for {0}.
        /// </summary>
        internal static string ResolveSceneRoll {
            get {
                return ResourceManager.GetString("ResolveSceneRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Challenge.
        /// </summary>
        internal static string SceneChallenge {
            get {
                return ResourceManager.GetString("SceneChallenge", resourceCulture);
            }
        }
    }
}
