//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.StarForged.Starships {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StarShipResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StarShipResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.StarForged.Starships.StarShipResources", typeof(StarShipResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstLook.
        /// </summary>
        internal static string FirstLook {
            get {
                return ResourceManager.GetString("FirstLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet.
        /// </summary>
        internal static string Fleet {
            get {
                return ResourceManager.GetString("Fleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Contact.
        /// </summary>
        internal static string InitialContact {
            get {
                return ResourceManager.GetString("InitialContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a space region:
        ///1️⃣ - Termnius
        ///2️⃣ - Outlands
        ///3️⃣ - Expanse.
        /// </summary>
        internal static string PickSpaceRegionMessage {
            get {
                return ResourceManager.GetString("PickSpaceRegionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship.
        /// </summary>
        internal static string Starship {
            get {
                return ResourceManager.GetString("Starship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Starship.
        /// </summary>
        internal static string StarshipDescription {
            get {
                return ResourceManager.GetString("StarshipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship Helper.
        /// </summary>
        internal static string StarshipHelperTitle {
            get {
                return ResourceManager.GetString("StarshipHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship Mission.
        /// </summary>
        internal static string StarshipMission {
            get {
                return ResourceManager.GetString("StarshipMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Starship Mission].
        /// </summary>
        internal static string StarshipMissionOracle {
            get {
                return ResourceManager.GetString("StarshipMissionOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship Mission {0}.
        /// </summary>
        internal static string StarshipMissionOracleRegionFormatter {
            get {
                return ResourceManager.GetString("StarshipMissionOracleRegionFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship Name.
        /// </summary>
        internal static string StarshipName {
            get {
                return ResourceManager.GetString("StarshipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship Type.
        /// </summary>
        internal static string StarshipType {
            get {
                return ResourceManager.GetString("StarshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typical Role.
        /// </summary>
        internal static string TypicalRole {
            get {
                return ResourceManager.GetString("TypicalRole", resourceCulture);
            }
        }
    }
}
