//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOracle.GameCore.Oracle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OracleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OracleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOracle.GameCore.Oracle.OracleResources", typeof(OracleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost Certain.
        /// </summary>
        internal static string AlmostCertain {
            get {
                return ResourceManager.GetString("AlmostCertain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a value between 1 and 99 or one of the following values:
        ///.
        /// </summary>
        internal static string AskCommandUnknownValue {
            get {
                return ResourceManager.GetString("AskCommandUnknownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the likelihood of it happening?
        ///1️⃣ - Almost Certain 
        ///2️⃣ - Likely
        ///3️⃣ - 50/50
        ///4️⃣ - Unlikely
        ///5️⃣ - Small Chance.
        /// </summary>
        internal static string AskOracleHelperMessage {
            get {
                return ResourceManager.GetString("AskOracleHelperMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __Ask The Oracle Helper__.
        /// </summary>
        internal static string AskOracleHelperTitle {
            get {
                return ResourceManager.GetString("AskOracleHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of.
        /// </summary>
        internal static string AskResult {
            get {
                return ResourceManager.GetString("AskResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50/50.
        /// </summary>
        internal static string FiftyFifty {
            get {
                return ResourceManager.GetString("FiftyFifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likely.
        /// </summary>
        internal static string Likely {
            get {
                return ResourceManager.GetString("Likely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Result.
        /// </summary>
        internal static string OracleResult {
            get {
                return ResourceManager.GetString("OracleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Table.
        /// </summary>
        internal static string OracleTable {
            get {
                return ResourceManager.GetString("OracleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        internal static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired Table(s):.
        /// </summary>
        internal static string PairedTable {
            get {
                return ResourceManager.GetString("PairedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        internal static string Roll {
            get {
                return ResourceManager.GetString("Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Chance.
        /// </summary>
        internal static string SmallChance {
            get {
                return ResourceManager.GetString("SmallChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many tables with that name, please specify a game: {0}. 
        ///To avoid this error in the future your set you default game with the `!SetDefaultGame` command.
        /// </summary>
        internal static string TooManyGamesError {
            get {
                return ResourceManager.GetString("TooManyGamesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Oracle Table:.
        /// </summary>
        internal static string UnknownTableError {
            get {
                return ResourceManager.GetString("UnknownTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlikely.
        /// </summary>
        internal static string Unlikely {
            get {
                return ResourceManager.GetString("Unlikely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vs.
        /// </summary>
        internal static string Verus {
            get {
                return ResourceManager.GetString("Verus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
